name: build-test-deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Build Spring Boot App
        run: ./mvnw clean install -DskipTests

      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build React App
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      # Add more steps if needed
