name: build-test-deploy

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js (for React app)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 👉 Build the React app (inside the 'frontend' folder)
      - name: Build React App
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      # Set up Java (for Spring Boot)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 👉 Build Spring Boot app (inside the 'demo' folder)
      - name: Build Spring Boot App
        working-directory: ./demo
        run: ./mvnw package

      # Add your deployment step here if needed (like Render, etc.)
