name: CI/CD - build & deploy to Render

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install & Build Frontend
        working-directory: frontend
        run: |
          npm ci
          npm test -- --watchAll=false || true
          npm run build

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    needs: build-frontend
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: test
          MYSQL_PASSWORD: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build backend (Maven)
        working-directory: demo
        run: |
          if [ -f ./mvnw ]; then
            chmod +x ./mvnw
            ./mvnw -B -DskipTests package
          else
            mvn -B -DskipTests package
          fi

  deploy:
    name: Trigger Render Deploys
    runs-on: ubuntu-latest
    needs: [build-frontend, build-backend]
    steps:
      - uses: actions/checkout@v4

      - name: Trigger frontend deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          FRONTEND_SERVICE_ID: ${{ secrets.FRONTEND_SERVICE_ID }}
        run: |
          echo "Triggering frontend deploy..."
          curl -X POST "https://api.render.com/v1/services/${FRONTEND_SERVICE_ID}/deploys" \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Accept: application/json"

      - name: Trigger backend deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          BACKEND_SERVICE_ID: ${{ secrets.BACKEND_SERVICE_ID }}
        run: |
          echo "Triggering backend deploy..."
          curl -X POST "https://api.render.com/v1/services/${BACKEND_SERVICE_ID}/deploys" \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Accept: application/json"
